####################
#Author(s):Alejandro Ortigas-Vasquez, David A. Kennedy
#Date:April 23, 2026
#Description:R script for generating Plink input files
#Inputs: Variant tables generated by "01_extract_snps_repeats_indels.R" script (SNP_Calls.txt,SNPLocations.txt)
#Outputs:Plink .ped,.phe,.map files
####################

# Extract variant table
Data=read.table("data/SNPCalls.txt", sep=",", stringsAsFactors=FALSE)
Positions=read.table("data/SNPLocations.txt", sep=",")
Positions=Positions[,1]

# Define chromosome-like region breakpoints
Breakpoints=c(12540.5, 59409.5, 76997.5, 132987.5, 134958.5, 145297.5)

# Create table for plink
FamilyID=c(1:nrow(Data))
IndividualID=as.character(Data[,1])
PaternalID=rep(0, nrow(Data))
MaternalID=rep(0, nrow(Data))
Sex=rep(1, nrow(Data))

# Define Pathotype (if using Pathotype for Phenotype)
#Phenotype=as.character(Data[,2])
#Phenotype[Phenotype=="v"]="0"
#Phenotype[Phenotype=="vv"]="0.5"
#Phenotype[Phenotype=="vv+"]="1.0"

# Declare Phenotype as Virulence Rank
Phenotype=as.character(Data[,3])

SNPs=ncol(Data)-5
Genotype=matrix("", nrow(Data), 2*SNPs)

for (j in 1:nrow(Data))
{
    Temp=Data[j,6:ncol(Data)]

    Genotype[j,seq(1,ncol(Genotype),2)]=as.character(Temp)
    Genotype[j,seq(2,ncol(Genotype),2)]=as.character(Temp)
}

Output1=cbind(FamilyID, IndividualID, PaternalID, MaternalID, Sex, Phenotype, Genotype)

write.table(Output1, file="data/MDVGenotypes2.ped", quote=FALSE, row.names=FALSE, col.names=FALSE)

Output2=cbind(FamilyID, IndividualID, Phenotype)
write.table(Output2, file="data/MDVqt2.phe", quote=FALSE, row.names=FALSE, col.names=FALSE)

# No Chromosomes
#Output3=cbind(1, Positions, 0, 1:SNPs)
#write.table(Output3, file="data/MDVGenotypes2.map", quote=FALSE, row.names=FALSE, col.names=FALSE)

# NRRs as Chromosomes
Chromosome=numeric()
for(i in 1:length(Positions))
{
    if(Positions[i]<max(Breakpoints))
    {
      Chromosome[i]=min(which((Breakpoints>Positions[i])==TRUE))
    }else
    {
      Chromosome[i]=7
    }
}
Output4=cbind(Chromosome, Positions, 0, 1:SNPs)
write.table(Output4, file="data/MDVGenotypes2.map", quote=FALSE, row.names=FALSE, col.names=FALSE)




