####################
#Author(s):Alejandro Ortigas-Vasquez, David A. Kennedy
#Date:April 23, 2026
#Description:R script for generating QQ-plots and Manhattan Plots for MDV GWAS
#Inputs: .mlma files generated by GCTA
#Outputs:QQ-plot and Manhattan Plot
####################
# Define functions
ggd.qqplot = function(pvector, main=NULL, ...) {
    o = -log10(sort(pvector,decreasing=F))
    e = -log10( 1:length(o)/length(o) )
    plot(e,o,pch=19,cex=1, main=main, ...,
		 xlab=expression(Expected~~(-log[10](italic(p)))),
		 ylab=expression(Observed~~(-log[10](italic(p)))),
		 xlim=c(0,max(e)), ylim=c(0,max(o)))
    abline(0,1, col="red")
}

pvalues_above_qqline = function(pvector) {
  # Clean p-values
  valid_idx = which(!is.na(pvector) & pvector > 0 & pvector <= 1)
  p_clean = pvector[valid_idx]
  n = length(p_clean)
  
  # Sort and compute observed/expected
  sorted_idx = order(p_clean)
  sorted_p = p_clean[sorted_idx]
  observed = -log10(sorted_p)
  expected = -log10(ppoints(n))
  
  # Identify where observed > expected
  above = observed > expected
  
  # Filter and return only those above the line
  return(data.frame(
    original_index = valid_idx[sorted_idx][above],
    p_value = sorted_p[above],
    observed = observed[above],
    expected = expected[above]
  ))
}

# No chromosomes + VR
# QassocMLMAData=read.table("data/MDVGenotypes2.mlma", header=TRUE)

# No chromosomes + Pathotype
# QassocMLMAData=read.table("data/MDVGenotypes2.mlma", header=TRUE)

# Chromosomes + VR
QassocMLMAData=read.table("data/MDVGenotypes2.loco.mlma", header=TRUE)

# Chromosome + Pathotype
# QassocMLMAData=read.table("data/MDVGenotypes2.loco.mlma", header=TRUE)

# Extract pvalues
PValues=as.numeric(QassocMLMAData[,9])
PValues=PValues[!is.na(PValues)]

# Generate QQ-Plot
ggd.qqplot(PValues, "QQ-plot, MLMA-LOCO")

# Generate pvalues table
observed_pvalues= -log10(sort(PValues,decreasing=F))
expected_pvalues= -log10(1:length(observed_pvalues)/length(observed_pvalues))

# Check points above expected line function
pvalues_above_expected<-pvalues_above_qqline(PValues)
write.csv(pvalues_above_expected, "data/pvalues_above_expected.csv", row.names = FALSE)

# Generate Manhattan Plot
ntests = 800
plot(QassocMLMAData$SNP, -log10(QassocMLMAData$p), ylim=c(0,7), main="MLMA-LOCO", xlab="Genome position", ylab="-log10(p)")
abline(h=-log10(0.05) + log10(ntests), col=2)

# SNP locations of all points above the line
QassocMLMAData$SNP[which(-log10(QassocMLMAData$p)>(-log10(0.05) +log10(ntests)))]  

  
  